import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { buildApp } from "../src/app.js";
import { describeRoutePolicy } from "../src/lib/route-policy.js";

const EXPECTED = {
  total: 278,
  public: 15,
  token: 12,
  authenticated: 30,
  capability: 170,
  contextual: 51,
};

function table(rows: Awaited<ReturnType<typeof buildApp>>["routePolicyLedger"]): string {
  return rows
    .filter((row) => row.method !== "HEAD")
    .sort((a, b) => a.url.localeCompare(b.url) || a.method.localeCompare(b.method))
    .map((row) => `| ${row.method} | \`${row.url}\` | ${describeRoutePolicy(row.policy)} |`)
    .join("\n");
}

const app = await buildApp();
try {
  const rows = app.routePolicyLedger.filter((row) => row.method !== "HEAD");
  const counts = Object.fromEntries(
    ["public", "token", "authenticated", "capability", "contextual"].map((kind) => [
      kind,
      rows.filter((row) => row.policy.kind === kind).length,
    ]),
  );
  const actual = { total: rows.length, ...counts };
  if (
    Object.entries(EXPECTED).some(
      ([key, expected]) => actual[key as keyof typeof actual] !== expected,
    )
  ) {
    throw new Error(
      `Route policy audit mismatch: ${JSON.stringify({ expected: EXPECTED, actual })}`,
    );
  }
  if (
    app.routePolicyExemptions.length !== 1 ||
    app.routePolicyExemptions[0]?.url !== "/api/auth/*" ||
    app.routePolicyExemptions[0]?.exemption !== "better-auth-generated"
  ) {
    throw new Error(
      `Unexpected route-policy exemptions: ${JSON.stringify(app.routePolicyExemptions)}`,
    );
  }

  const document = `# API route-policy ledger\n\n> Generated by \`pnpm --filter @hackos/api route-policy:audit\`. Do not edit manually.\n\nThe runtime has **${rows.length} non-HEAD application route rows** plus the single Better Auth generated-route exemption (\`/api/auth/*\`), for **${rows.length + 1} logical declarations**. The current inventory includes self/staff secondary-email removal and the capability-scoped project-member candidate search; HEAD auto-routes are intentionally excluded.\n\n| Policy kind | Rows |\n| --- | ---: |\n| public | ${counts.public} |\n| token | ${counts.token} |\n| authenticated | ${counts.authenticated} |\n| capability | ${counts.capability} |\n| contextual | ${counts.contextual} |\n| **total** | **${rows.length}** |\n\nPublic/token snapshot: public rows are health, public content/announcement/TV/invalidation only; token rows are invite, confirmation, verification resend, scoped wallet access, and Apple PassKit protocol flows. The sole exemption is Better Auth's generated \`/api/auth/*\` catch-all.\n\n| Method | Path | Policy |\n| --- | --- | --- |\n${table(rows)}\n`;
  const destination = resolve(import.meta.dirname, "../../../docs/access-control-route-ledger.md");
  await writeFile(destination, document);
  console.log(
    `route-policy audit passed: ${rows.length} rows, ${app.routePolicyExemptions.length} exemption`,
  );
} finally {
  await app.close();
}

// Building the complete application initializes shared Redis/BullMQ handles
// that are intentionally process-scoped. This is a standalone audit command;
// all output has been awaited, so terminate those handles after a clean audit.
process.exit(0);
